name: 'Nightly Merge'

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  nightly-merge:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3.1.0

    - name: Nightly Merge
      uses: robotology/gh-action-nightly-merge@22f5e45d028f22837d617fa07512925457eec184
      with:
        stable_branch: 'RELEASE_next_patch'
        development_branch: 'RELEASE_next_minor'
        allow_ff: true
        allow_forks: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
